name: phpstan
on: [pull_request]
jobs:
  phpstan:
    name: runner / phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: 7.3
          tools: composer:v2
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, gd
      - name: Composer install
        run: 'COMPOSER_MEMORY_LIMIT=-1 composer install'
      - name: PHPStan
        run: 'php vendor/bin/phpstan analyze docroot/modules/custom docroot/themes/custom tests'
